<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(CommonTargetFramework)</TargetFramework>
    <RootNamespace>Squire.ConwayLife</RootNamespace>
    <OutputType>Exe</OutputType>
    <StartupObject>Squire.ConwayLife.EntryPoint</StartupObject>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
